Resources:
  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "gameId"
          AttributeType: "S"
        - AttributeName: "owner"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "gameId"
          KeyType: "HASH"
        - AttributeName: "owner"
          KeyType: "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Games"

  PlayersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "playerId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "playerId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "Players"